In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("C:\Ruquayya Banu\Data Science\Datasets\Social_Network_Ads.csv")

In [3]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
# age and gender is not useful so drop it

In [5]:
# seperating input and target features:

x=df.iloc[:,2:4]
y=df.iloc[:,-1]

In [6]:
x

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [7]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [8]:
# splitting the data into train and test:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=45)

In [9]:
# implement start of support vector machine- classification

In [10]:
from sklearn.svm import SVC
classifier=SVC(kernel="rbf") #rbf is gaussian kernal - hyper parameter tuning later
classifier.fit(x_train,y_train)

SVC()

In [11]:
# training score
y_train_pred=classifier.predict(x_train)
y_train_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# predicting the values for the test set - test score
y_pred_test=classifier.predict(x_test)
y_pred_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# checking the accuracy
from sklearn.metrics import accuracy_score
print("Accuracy of the model for train data",accuracy_score(y_train_pred,y_train))
print("Accuracy of the model for test data",accuracy_score(y_test,y_pred_test))
# this model is not overfitted , not high bias

Accuracy of the model for train data 0.7928571428571428
Accuracy of the model for test data 0.725

- Parameter to perform hyperparameter tuning in SVM

1. Gamma : is something which we use for non- linear kernals such as RBF (Radial Basis Function) or polynomial to control the flecibility and complexity of the model. It control the spread of kernal influence.
- hyper parameter tune it to find the good value of gama.
- Gamma value (high)- decision bounday is complex. (overfitting)
- Gamma value (low)- very smooth.   (underfit)


2. Kernel - responsible for feature engineering.

3. C - C is nothing but a distance of your margin form the hyperplane. parmeter which controls the trade off between achieving a wide decision margin and minimizing missclassification errors. It is a hyperparameter needed to be tuned for good model performance on unseen data.

In [14]:
# performing hyper parameter tunning in svm
# select very small value of gamma
# c is for margin width - it has to always tunned it - to reduce the misclassified data points
# second tunning is linear kernal.
# other kernals we can mentioned it - if required
tuned_parameters=[{"kernel":["rbf"],"gamma":[np.random.rand(3)],"C":[1,10,100,20,1000]},
                  {"kernel":["linear"],"C":[1,10,100,20,1000]}]
tuned_parameters

[{'kernel': ['rbf'],
  'gamma': [array([0.92489259, 0.27801312, 0.03340612])],
  'C': [1, 10, 100, 20, 1000]},
 {'kernel': ['linear'], 'C': [1, 10, 100, 20, 1000]}]

In [15]:
# cross validation should be perform only on training data not on test data for any algo

In [ ]:
# cross validation 
from sklearn.model_selection import GridSearchCV
clf= GridSearchCV(estimator=SVC(), # model- support vector classifier
                  param_grid=tuned_parameters, # hyper parameter tunning need to give
                  scoring="accuracy", # basis of accuracy
                  cv=5, # k fold for every 50 fits
                  return_train_score=True, # train score return after validation 
                  verbose=1 # summary in one line
                  )

clf.fit(x_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

In [ ]:
1. Outliers Treatment In the real world/ when we join the company trimming/Capping/transformation which would be the best practice
or it depends on the company/client requirement.
    Ans- trimming for very less entries,capping for so many entries,transformation is when you have data like payment,
         salary which actual require log transformation.
2. R2score  (train,test) is like we can see the variances and based on that we can judge the overfitting or underfitting and decide
whether best performer or poor performer . but what insights or knowledge i will gain from MAE, MSE,RMSE .
   Ans - based on outlier will choose it.
3. I was doing the hyperparameter tuning for the first assignment which is KNN . So there is p, n_neighbors and there is also
weights is it required to tune weights or we can ignore it ?
  Ans - Not required, no tunning

In [ ]:
# then put the values of svm and re do all the svm implementation