In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("C:/Ruquayya Banu/Data Science/Datasets/Social_Network_Ads.csv")

In [3]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [4]:
# we have to identify on the basis of the given information if the customer is going to purchase to ads or not

In [5]:
#categorie column
# this column is imbalanced because zero's are more then one's
df["Purchased"].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [6]:
# splitting the input and target feature

# input feature- Gender Age EstimatedSalary	- columns	  
x = df.iloc[:,1:4]

# target feature - Purchased - column
y = df.iloc[:,4:]

In [7]:
x

     Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [8]:
y

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [9]:
#splitting the data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.3,random_state=56)
print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(280, 3) (120, 3)
(280, 1) (120, 1)

In [10]:
# gender is a categoring column- it is nominal - so using one hot encoding technique

In [11]:
# Encoding the gender column - for trained data
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop = "first", sparse_output = False) # drop will remove the last column so in output female category will not get
one_hot_encoded = encoder.fit_transform(x_train[["Gender"]]) #output it will give it in array format

# array Convert to DataFrame
x_train_trans = pd.DataFrame(
    one_hot_encoded,
    columns=encoder.get_feature_names_out(["Gender"]),
    index=x_train.index
)
x_train_trans

     Gender_Male
313          0.0
18           1.0
40           0.0
54           0.0
189          1.0
..           ...
142          1.0
122          0.0
235          1.0
192          1.0
341          1.0

[280 rows x 1 columns]

In [12]:
# Encoding the gender column - for test data
one_hot_encoded = encoder.transform(x_test[["Gender"]]) #output it will give it in array format

# array Convert to DataFrame
x_test_trans = pd.DataFrame(
    one_hot_encoded,
    columns=encoder.get_feature_names_out(["Gender"]),
    index=x_test.index
)
x_test_trans

     Gender_Male
79           0.0
112          1.0
164          0.0
185          1.0
180          1.0
..           ...
198          1.0
172          0.0
99           0.0
351          1.0
24           1.0

[120 rows x 1 columns]

In [13]:
# merging the encoded feature into train data
x_train["Gender"]= x_train_trans
x_train

     Gender  Age  EstimatedSalary
313     0.0   49           141000
18      1.0   46            28000
40      0.0   27            17000
54      0.0   27            58000
189     1.0   28            32000
..      ...  ...              ...
142     1.0   35            59000
122     0.0   40            75000
235     1.0   46            79000
192     1.0   29            43000
341     1.0   35            75000

[280 rows x 3 columns]

In [14]:
# merging the encoded feature into test data
x_test[["Gender"]] = x_test_trans
x_test

     Gender  Age  EstimatedSalary
79      0.0   26            17000
112     1.0   38            61000
164     0.0   33            69000
185     1.0   31            66000
180     1.0   26            16000
..      ...  ...              ...
198     1.0   26            80000
172     0.0   26           118000
99      0.0   28            37000
351     1.0   37            75000
24      1.0   46            23000

[120 rows x 3 columns]

In [15]:
# ******* above code is now made data ready to fit in your ML model **********

In [16]:
df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [17]:
# deciding the value of "k" 
# square root of count of training data points

import numpy as np
np.sqrt(x_train.shape[0]) #zero index

np.float64(16.73320053068151)

In [18]:
x_train.shape

(280, 3)

In [19]:
# KNN Classification 
from sklearn.neighbors import KNeighborsClassifier
knn =  KNeighborsClassifier(n_neighbors= 17)
# fitting a data into the knn model
knn.fit(x_train, y_train)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=17)

In [20]:
# prediciton 
y_pred = knn.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [21]:
#actual value 
# y_test.values  #in array format you will get output
y_test

     Purchased
79           0
112          0
164          0
185          0
180          0
..         ...
198          0
172          0
99           0
351          0
24           1

[120 rows x 1 columns]

In [22]:
# finding accuracy of KNN model

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7916666666666666

In [23]:
# 79.16% accuracy in this model we got

In [24]:
# error metrics in classification models are:-
# confusion matrix
# accuracy score
# precision
#recall

In [25]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[72,  5],
       [20, 23]])

In [26]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.94      0.85        77
           1       0.82      0.53      0.65        43

    accuracy                           0.79       120
   macro avg       0.80      0.73      0.75       120
weighted avg       0.80      0.79      0.78       120

In [27]:
# benefits of precision
# precision = TP/predicted yes
# high precision means model is good at correctly identify positive cases and avoid incorrect labelling of negavtive cases as positive.
# a high precisin spam filter will be very reliable in not making important email as spam, ensuring legitimate message are n ot missed.

In [28]:
#benifits of recall
# recall = TP/Actual yes
# high recall indicates that model is good at identifying all actual positive cases are not missing them.
# a high recall model will flag as many fraudulant transactions as possible minimizing the financial los.

In [30]:
# benifits of F1 Score
# F1= 2*precision*recall/(precision +recall)
# it is a measure of a model's predicition in ML calculated as the harmonic mean of precision and recall.
# particularly useful for imbalanced data.
#F1 Score is valuable in application like spam and fraud dectection where FP and FN both can have significance consequences.