In [75]:
import pandas as pd

In [77]:
df=pd.read_csv("/Users/meghaprajapati/Downloads/2121048-22_May_2023_Diamonds_Advnaced_Case_Study/diamonds.csv")
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

# Case Study - Diamond Price Prediction:

### Business Understanding:

Diamond is one of the strongest and the most valuable substances produced naturally as a form of carbon.
However, unlike gold and silver, determining the price of a diamond is very complex because many features are to be considered for
determining its price.
The value of diamonds depends upon their structure, cut, inclusions (impurity), carats, and many other features. 
The uses of diamonds are many, such as in industries, as they are effective in cutting, polishing, and drilling.
Since diamonds are extremely valuable, they have been traded across different countries for centuries now and this trade only increases 
with time. They are graded and certified based on the "four Cs", which are color, cut, clarity, and carat. These are the only metrics 
that are being used to the quality of diamonds and sets the price of the diamond. This metric allows uniform understanding for people
across the world to buy diamonds, which allows ease of trade and value for what is purchased.

#### Understanding the 4 C's

- Cut
- Color
- Clarity
- Carat


1. price- price in US dollars
2. carat- weight of the diamonds
3. cut- quality of the cut
4. clarity- a measurement of how clear the diamond is 
5. x= length in mm
6. y= width in mm
7. z= depth in mm
8. depth=  total depth percentage = z/mean(x,y)
9. table= width of top of diamond relative to widest point.

In [80]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [82]:
df.shape

(53940, 10)

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [86]:
df.isnull().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

In [88]:
df.describe(include="all")

,carat,cut,color,clarity,depth,table,price,x,y,z
count,53940.000000,53940,53940,53940,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
unique,NaN,5,7,8,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Ideal,G,SI1,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,21551,11292,13065,NaN,NaN,NaN,NaN,NaN,NaN
mean,0.797940,NaN,NaN,NaN,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,NaN,NaN,NaN,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,NaN,NaN,NaN,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,NaN,NaN,NaN,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,NaN,NaN,NaN,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,NaN,NaN,NaN,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,NaN,NaN,NaN,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

# Observations:

1. There are nearly 53940 data points with 10 features.
2. Almost all the numerical features are normally distributed except the price as the better quality diamond will have higher price
   as comapred to that of lowered quality diamonds.

In [91]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [93]:
df["cut"].value_counts()

cut
Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: count, dtype: int64

In [95]:
df["color"].value_counts()

color
G    11292
E     9797
F     9542
H     8304
D     6775
I     5422
J     2808
Name: count, dtype: int64

In [97]:
df["clarity"].value_counts()

clarity
SI1     13065
VS2     12258
SI2      9194
VS1      8171
VVS2     5066
VVS1     3655
IF       1790
I1        741
Name: count, dtype: int64

In [99]:
df=df.rename(columns={'x': 'length', 'y':'width', 'z': 'depth',"depth":"depth_percentage"})

In [101]:
df

,carat,cut,color,clarity,depth_percentage,table,price,length,width,depth
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75
...,...,...,...,...,...,...,...,...,...,...
53935,0.72,Ideal,D,SI1,60.8,57.0,2757,5.75,5.76,3.50
53936,0.72,Good,D,SI1,63.1,55.0,2757,5.69,5.75,3.61
53937,0.70,Very Good,D,SI1,62.8,60.0,2757,5.66,5.68,3.56
53938,0.86,Premium,H,SI2,61.0,58.0,2757,6.15,6.12,3.74
53939,0.75,Ideal,D,SI2,62.2,55.0,2757,5.83,5.87,3.64

In [103]:
df.loc[(df["length"]==0) |(df["width"]==0) | (df["depth"]==0)]

,carat,cut,color,clarity,depth_percentage,table,price,length,width,depth
2207,1.00,Premium,G,SI2,59.1,59.0,3142,6.55,6.48,0.0
2314,1.01,Premium,H,I1,58.1,59.0,3167,6.66,6.60,0.0
4791,1.10,Premium,G,SI2,63.0,59.0,3696,6.50,6.47,0.0
5471,1.01,Premium,F,SI2,59.2,58.0,3837,6.50,6.47,0.0
10167,1.50,Good,G,I1,64.0,61.0,4731,7.15,7.04,0.0
11182,1.07,Ideal,F,SI2,61.6,56.0,4954,0.00,6.62,0.0
11963,1.00,Very Good,H,VS2,63.3,53.0,5139,0.00,0.00,0.0
13601,1.15,Ideal,G,VS2,59.2,56.0,5564,6.88,6.83,0.0
15951,1.14,Fair,G,VS1,57.5,67.0,6381,0.00,0.00,0.0
24394,2.18,Premium,H,SI2,59.4,61.0,12631,8.49,8.45,0.0
24520,1.56,Ideal,G,VS2,62.2,54.0,12800,0.00,0.00,0.0
26123,2.25,Premium,I,SI1,61.3,58.0,15397,8.52,8.42,0.0
26243,1.20,Premium,D,VVS1,62.1,59.0,15686,0.00,0.00,0.0
27112,2.20,Premium,H,SI1,61.2,59.0,17265,8.42,8.37,0.0
27429,2.25,Premium,H,SI2,62.8,59.0,18034,0.00,0.00,0.0
27503,2.02,Premium,H,VS2,62.7,53.0,18207,8.02,7.95,0.0
27739,2.80,Good,G,SI2,63.8,58.0,18788,8.90,8.85,0.0
49556,0.71,Good,F,SI2,64.1,60.0,2130,0.00,0.00,0.0
49557,0.71,Good,F,SI2,64.1,60.0,2130,0.00,0.00,0.0
51506,1.12,Premium,G,I1,60.4,59.0,2383,6.71,6.67,0.0

In [105]:
len(df.loc[(df["length"]==0) |(df["width"]==0) | (df["depth"]==0)])

20

# Observation:

There are 20 data points which have 0 in one or the another column. Since the no. of data points with 0 are very less comapred to the
total number of data points deleting them wont effect the data.

deleting all the data points containing 0.