In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/Users/meghaprajapati/Downloads/Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
# we have to identify on the basis of the given information if the customer is going to purchase the ad or not.

df["Purchased"].value_counts()  # data is imbalanced in nature and will cover this topic in future.

Purchased
0    257
1    143
Name: count, dtype: int64

In [4]:
# splitting the input and the target features.

x=df.iloc[:,1:4]
y=df.iloc[:,4:]

In [5]:
x

     Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [6]:
y

     Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

In [7]:
# splitting the data into train and test

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=56)

print(x_train.shape,x_test.shape)
print(y_train.shape,y_test.shape)

(280, 3) (120, 3)
(280, 1) (120, 1)

In [8]:
x_train

     Gender  Age  EstimatedSalary
313  Female   49           141000
18     Male   46            28000
40   Female   27            17000
54   Female   27            58000
189    Male   28            32000
..      ...  ...              ...
142    Male   35            59000
122  Female   40            75000
235    Male   46            79000
192    Male   29            43000
341    Male   35            75000

[280 rows x 3 columns]

In [9]:
# Encoding the gender column

from sklearn.preprocessing import OneHotEncoder

encoder=OneHotEncoder(drop="first",sparse_output=False)

one_hot_encoded=encoder.fit_transform(x_train[["Gender"]])
one_hot_encoded
x_train_trans=pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(["Gender"]),index=x_train["Gender"].index)
x_train_trans

     Gender_Male
313          0.0
18           1.0
40           0.0
54           0.0
189          1.0
..           ...
142          1.0
122          0.0
235          1.0
192          1.0
341          1.0

[280 rows x 1 columns]

In [16]:
one_hot_encoded=encoder.transform(x_test[["Gender"]])
one_hot_encoded
x_test_trans=pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(["Gender"]),index=x_test["Gender"].index)
x_test_trans

     Gender_Male
79           0.0
112          1.0
164          0.0
185          1.0
180          1.0
..           ...
198          1.0
172          0.0
99           0.0
351          1.0
24           1.0

[120 rows x 1 columns]

In [17]:
# merging the encoded feature into train and test data.

x_train["Gender"]=x_train_trans
x_train
x_test["Gender"]=x_test_trans

In [18]:
x_train,x_test

(     Gender  Age  EstimatedSalary
 313     0.0   49           141000
 18      1.0   46            28000
 40      0.0   27            17000
 54      0.0   27            58000
 189     1.0   28            32000
 ..      ...  ...              ...
 142     1.0   35            59000
 122     0.0   40            75000
 235     1.0   46            79000
 192     1.0   29            43000
 341     1.0   35            75000

 [280 rows x 3 columns],
      Gender  Age  EstimatedSalary
 79      0.0   26            17000
 112     1.0   38            61000
 164     0.0   33            69000
 185     1.0   31            66000
 180     1.0   26            16000
 ..      ...  ...              ...
 198     1.0   26            80000
 172     0.0   26           118000
 99      0.0   28            37000
 351     1.0   37            75000
 24      1.0   46            23000

 [120 rows x 3 columns])

In [19]:


df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [20]:
# deciding the value of k

# sqaure root of count of training data points

import numpy as np
np.sqrt(x_train.shape[0])

16.73320053068151

In [21]:
x_train.shape

(280, 3)

In [31]:
# model application

from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=17)
knn.fit(x_train,y_train)

/Users/meghaprajapati/opt/anaconda3/lib/python3.12/site-packages/sklearn/neighbors/_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier(n_neighbors=17)

In [33]:
# prediction:

y_pred=knn.predict(x_test)

In [35]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [37]:
y_test

     Purchased
79           0
112          0
164          0
185          0
180          0
..         ...
198          0
172          0
99           0
351          0
24           1

[120 rows x 1 columns]

In [39]:
# finding the accuracy of the model

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7916666666666666

 # Error or accuracy metrics in classification models.

 - Confusion matrix
 - accuracy score
 - precision
 - recall

In [43]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test,y_pred)

array([[72,  5],
       [20, 23]])

In [47]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.94      0.85        77
           1       0.82      0.53      0.65        43

    accuracy                           0.79       120
   macro avg       0.80      0.73      0.75       120
weighted avg       0.80      0.79      0.78       120

# Benefits of precision

- precision= TP/predicted yes
- High precision means model is good at correctly identifying positive cases and avoids incorrect labelling of negative cases as positive.
- A high precision spam filter will be very reliable in not marking important emails as spam, ensuring legitimate messages are not
  missed.

# Benefits of recall:

- recall= TP/Actual_yes
- high recall indicates that model is good at identifying all actual positive cases and not missing them.
- A high recall model will flag as many fraudlent transactions as possible minimizing the financial loss.

# Benefits of F1 score:
- F1= 2*precision*recall/(precision +recall)
- it is a measure of a model's prediction in ML calculated as the harmonic mean of precisiomn and recall.
- Particularly useful for imabalanced data.
- F1 score is valauble in applications like spam detection and fraud detection where FP and FN both can have significant consequences.